name: Conditionals

on:
  push:
    branches: [main]
jobs:
  build:
    if: github.repository == 'misbahulhoq/Github-Examples'
    runs-on: ubuntu-latest
    steps:
      - name: "Building"
        run: echo "Building the application..."

  test:
    if: ${{github.repository_owner != 'misbahulhoq'}}
    runs-on: ubuntu-latest
    steps:
      - name: "Testing"
        run: echo "Testing the application..."
